### ISSUE TITLE
Invalid Resource Property (SecurityHubFindingsToMSTeams.yaml)

### ISSUE THREAD

**Issue by thedudedownthestreet** [aws-samples/aws-securityhub-findings-to-msteams#1]
Invalid template resource property 'cfn_nag" when importing into cloud formation.

**Comment by j-chan-scb** [comment]
cfn_nag is at the wrong indent level for some reason.

```
lambdafindingsToMSTeams:
  Metadata:
    checkov:
      skip:
        - id: "CKV_AWS_115"
          comment: "Example code - ReservedConcurrentExecutions may be considered in a Production environment to guarantee Lambda is launched"
        # other checkov skips...
  cfn_nag:
    rules_to_suppress:
      - id: W89
        reason: "Example code - Running a Lambda inside a VPC should be considered for a Production environemnt."
      # other rules...

```

should be:
```
lambdafindingsToMSTeams:
  Metadata:
    checkov:
      skip:
        - id: "CKV_AWS_115"
          comment: "Example code - ReservedConcurrentExecutions may be considered in a Production environment to guarantee Lambda is launched"
        # other checkov skips...
    cfn_nag:
      rules_to_suppress:
        - id: W89
          reason: "Example code - Running a Lambda inside a VPC should be considered for a Production environemnt."
        # other rules...

```
